### ISSUE TITLE
Log same chat twice

### ISSUE THREAD

**Issue by dilushan** [thomasleveil/b3-plugin-chatlogger#7]
I have facing strange problem that it logs every chat twice. So file size become doubles. And harder to read. I double checked whether I have included chatlogger twice in b3.XML. But its not. What could be the issue.

**Comment by thomasleveil** [comment]
makes sure B3 isn't running twice

**Comment by dilushan** [comment]
I running multiple instances for multiple servers in same machine. I thought they were independent. I'm not running same b3.XML twice. There are different b3.XML and plugin files for each servers

**Comment by thomasleveil** [comment]
Please post a support request on the B3 forums with your b3.log and config file.
